export const checkoutMock = {
  billingAddress: {
    __typename: 'Address',
    city: 'CALLAO - BELLAVISTA',
    country: {
      __typename: 'CountryDisplay',
      code: 'PE',
      country: 'Perú',
    },
    countryArea: '',
    firstName: 'Halley Rios',
    id: 'QWRkcmVzczo2MTI3',
    lastName: '',
    phone: '+51987765432',
    streetAddress1: 'Av. Perú, San Martín de Porres, Perú',
    streetAddress2: '',
  },
  dataTreatmentPolicy: false,
  documentNumber: '44042878',
  email: 'hriosv@auna.pe',
  id: 'Q2hlY2tvdXQ6Y2ZhNTJlNjUtZWNkNC00YzIyLThkZjItM2Y3MTAyODdlNmMy',
  scheduleDate: null,
  shippingAddress: {
    __typename: 'Address',
    city: 'CALLAO - CARMEN DE LA LEGUA',
    country: {
      __typename: 'CountryDisplay',
      code: 'PE',
      country: 'Perú',
    },
    countryArea: '',
    firstName: 'Halley Rios',
    id: 'QWRkcmVzczos2MTI1',
    lastName: '',
    phone: '+51987765432',
    streetAddress1: 'Av. Perú, San Martín de Porres, Perú',
    streetAddress2: 'la referencia',
  },
  shippingMethod: {
    __typename: 'ShippingMethod',
    id: 'U2hpcHBpbmdNZXRob2Q6NTE=',
    isScheduled: false,
    methodType: {
      id: 'ididid',
      code: 'express',
      name: 'express',
    },
    name: 'Miércoles 20/03 de 5 pm a 9 pm',
    price: {
      __typename: 'Money',
      amount: 5,
      culture: 'es-PE',
      currency: 'PEN',
    },
    scheduleDates: null,
    subtitle: null,
  },
  termsAndConditions: true,
  token: 'cfa52e65-ecd4-4c22-8df2-3f710287e6c2',
};

export const PROPS_LINE_DETAIL = {
  label: 'LabelText',
  text: 'textLine',
};
