version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.7.0-browsers
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: sudo apt-get install -y libpng-dev
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run typescript checker
          command: npx tsc --noEmit & npx tsc --noEmit -p src/@sdk & npx tsc --noEmit -p src/@next
      - run:
          name: Run tslint
          command: npm run tslint
      - run:
          name: Build application
          command: npm run build
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Package lock security test
          command: npx lockfile-lint --path package-lock.json --allowed-hosts npm yarn
      - run:
          name: lhci autorun
          command: npx lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
      - persist_to_workspace:
          root: ~/app
          paths:
            - dist/*
  cypress/run:
    docker:
      - image: cypress/base:10
        environment:
          TERM: xterm
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Npm CI
          command: npm ci
      - run:
          command: npx cypress verify
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - persist_to_workspace:
          root: ~/
          paths:
            - project
            - .cache/Cypress
      - attach_workspace:
          at: ~/
      - run:
          name: Running E2E tests
          command: npm run test:e2e:run
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

  deploy:
    working_directory: ~/app
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - attach_workspace:
          at: .
      - aws-s3/sync:
          arguments: |
            --delete
          #   --acl public-read \
          #   --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: '.'
          to: "s3://${STORE_WEB_BUCKET_S3}-${ENV}/"
          #overwrite: true
      - run: aws cloudfront create-invalidation --distribution-id ${CF_STORE_ID} --paths "/*"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          context: frontend-qa
          filters:
            branches:
              only: cicd
          requires:
            - build
      - deploy:
          context: frontend-stg
          filters:
            branches:
              only: cicd-stg
          requires:
            - build

      # - build:
      #     filters:
      #       tags:
      #         only: /^v.*/
      # - deploy:
      #     requires:
      #       - build
      #     filters:
      #       tags:
      #         only: /^v.*/
      #       branches:
      #         ignore: /.*/
      - cypress/run
