interface ICity {
  label: string;
  enabled?: boolean;
}
const cities: ICity[] = [
  { label: "Ancón" },
  { label: "Ate Vitarte" },
  { label: "Ate - La Merced", enabled: true },
  { label: "Ate - Salamanca", enabled: true },
  { label: "Barranco", enabled: true },
  { label: "Bellavista", enabled: true},
  { label: "Breña", enabled: false },
  { label: "Cañete-Asia", enabled: false },
  { label: "Carabayllo" },
  { label: "Carmen de la Legua", enabled: false},
  { label: "Chaclacayo" },
  { label: "Chilca", enabled: false },
  { label: "Chorrillos" },
  { label: "Cieneguilla" },
  { label: "Comas" },
  { label: "El Agustino" },
  { label: "Independencia" },
  { label: "Jesús María", enabled: true },
  { label: "La Encantada de Villa ", enabled: false },
  { label: "La Molina", enabled: true },
  { label: "La Perla", enabled: true},
  { label: "La Victoria", enabled: true },
  { label: "Lima" },
  { label: "Lince", enabled: true },
  { label: "Los Olivos" },
  { label: "Lurigancho" },
  { label: "Lurín" },
  { label: "Magdalena del Mar", enabled: true },
  { label: "Mala", enabled: false },
  { label: "Miraflores", enabled: true },
  { label: "Pachacamac" },
  { label: "Pucusana", enabled: false },
  { label: "Pueblo Libre", enabled: true },
  { label: "Puente Piedra" },
  { label: "Punta Hermosa", enabled: false },
  { label: "Punta Negra", enabled: false },
  { label: "Rímac" },
  { label: "San Bartolo", enabled: false },
  { label: "San Borja", enabled: true },
  { label: "San Isidro", enabled: true },
  { label: "San Juan de Lurigancho" },
  { label: "San Juan de Miraflores" },
  { label: "San Luis", enabled: true },
  { label: "San Martín de Porres" },
  { label: "San Miguel", enabled: true },
  { label: "Santa Anita", enabled: true },
  { label: "Santa María del Mar", enabled: false },
  { label: "Santa Rosa" },
  { label: "Santiago de Surco", enabled: true },
  { label: "Surquillo", enabled: true },
  { label: "Villa El Salvador" },
  { label: "Villa María del Triunfo" },
];

export const citiesOptions: string[] = cities.filter(city => city.enabled).map(city => city.label);
