on:
  pull_request:
    branches: [master, release]

jobs:
  build:
    name: "STOREFRONT CI "
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: 1- Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: 2- Install dependencies
        run: npm install
      - name: 3- Run typescript checker
        run: npx tsc --noEmit & npx tsc --noEmit -p src/@sdk & npx tsc --noEmit -p src/@next
      - name: 4- Run tslint
        run: npm run tslint
      - name: 5- Build application master ${{ github.event.pull_request.base.ref }} - by ${{ github.actor }}
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'master' }}
        run: npm run build
        env:
          API_URI: ${{ secrets.GRAPHQL_URL_QA }}
      - run: echo ${{ secrets.GRAPHQL_URL_QA }}
      - run: echo ${{ secrets.SENTRY_DSN_QA }}
      - name: 5- Build application release ${{ github.event.pull_request.base.ref }} - by ${{ github.actor }}
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'release' }}
        run: npm run build
        env:
          API_URI: ${{ secrets.GRAPHQL_URL_PROD }}
      - name: 6- Run tests
        run: npm run test
