name: CREATE-SENTRY-RELEASE
on:
  push:
    branches: [release]
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  Bump-Version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create Sentry release
      uses: getsentry/action-release@v1.0.0
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN_PRD }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG_PRD }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT_PRD }}
      with:
        environment: prod
        version_prefix: storefront@
