name: Lighthouse CI
on: 
  pull_request:
    branches: [ master ]
    paths-ignore:
    - '.github/**'

jobs:
  lighthouseci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      NEXT_PUBLIC_API_URI: ${{ secrets.GRAPHQL_URL_QA }}
      NEXT_PUBLIC_CDN_URL: ${{ secrets.CDN_URL_QA }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run lhci