name: TAGGING-RELEASE
on:
  push:
    branches: [release]
    paths-ignore:
    - '.github/**'
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  Bump-Version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Bump version and push tag
      id: "tag"
      uses: "anothrNick/github-tag-action@1.30.0"
      env:
        DEFAULT_BUMP: minor
        GITHUB_TOKEN: ${{ secrets.GHA_GITHUB_TOKEN }}
        REPO_OWNER: farmacia-retail
        WITH_V: true
        RELEASE_BRANCHES: release.*
        DRY_RUN: true
